### PR TITLE
chore: add sample nuxt app

### PR DESCRIPTION
**Pull request by rdunk**
Adds a sample Nuxt application alongside the Next.js example.

Uses a wrapper component to demonstrate toggling visual editing which can be applied to any Vue 3 app, rather than using Nuxt specific app hooks.

### CODE REVIEW

**Comment by rdunk** [comment]
Relevant issue for reasoning behind using `shamefully-hoist` at root level related to Nuxt and pnpm not playing nicely together.

https://github.com/nuxt/nuxt/issues/14146

**Comment by stipsan** [comment]
Socket is a bit over-eager here, ignore it.

@SocketSecurity ignore @nuxt/telemetry@2.4.1

**Review by stipsan — APPROVED** [review]
Looks good! The hoisting should be fine.
The Vercel build error, and the other errors, seems to be because I forgot to add a `turbo.json`. I'll fix that after merging :D

**Comment by stipsan** [comment]
@SocketSecurity ignore @nuxt/telemetry@2.4.1

**Pull request merged**
